# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_system_ila_1_0/system_system_ila_1_0.xci
# IP: The module: 'system_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/bd_15e9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_15e9 || ORIG_REF_NAME==bd_15e9} -quiet] -quiet

# IP: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/bd_15e9_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] -quiet

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/bd_15e9_ila_lib_0_ooc.xdc

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/bd_15e9_ooc.xdc

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/system_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_system_ila_1_0/system_system_ila_1_0.xci
# IP: The module: 'system_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/bd_15e9.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_15e9 || ORIG_REF_NAME==bd_15e9} -quiet] -quiet

# IP: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/bd_15e9_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] -quiet

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/bd_15e9_ila_lib_0_ooc.xdc

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/bd_15e9_ooc.xdc

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/ip/system_system_ila_1_0/system_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
