-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2022.2 (lin64) Build 3671981 Fri Oct 14 04:59:54 MDT 2022
-- Date        : Wed Apr 10 16:53:01 2024
-- Host        : G-P-SHAHAMZ-LW running 64-bit Ubuntu 20.04.6 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top system_util_daq2_xcvr_0 -prefix
--               system_util_daq2_xcvr_0_ system_util_daq2_xcvr_0_stub.vhdl
-- Design      : system_util_daq2_xcvr_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z045ffg900-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity system_util_daq2_xcvr_0 is
  Port ( 
    up_rstn : in STD_LOGIC;
    up_clk : in STD_LOGIC;
    qpll_ref_clk_0 : in STD_LOGIC;
    up_qpll_rst_0 : in STD_LOGIC;
    cpll_ref_clk_0 : in STD_LOGIC;
    up_cpll_rst_0 : in STD_LOGIC;
    rx_0_p : in STD_LOGIC;
    rx_0_n : in STD_LOGIC;
    rx_out_clk_0 : out STD_LOGIC;
    rx_clk_0 : in STD_LOGIC;
    rx_charisk_0 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_disperr_0 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_notintable_0 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_data_0 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    rx_calign_0 : in STD_LOGIC;
    rx_header_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    rx_block_sync_0 : out STD_LOGIC;
    tx_0_p : out STD_LOGIC;
    tx_0_n : out STD_LOGIC;
    tx_out_clk_0 : out STD_LOGIC;
    tx_clk_0 : in STD_LOGIC;
    tx_charisk_0 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    tx_data_0 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    tx_header_0 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_cm_enb_0 : in STD_LOGIC;
    up_cm_addr_0 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_0 : in STD_LOGIC;
    up_cm_wdata_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_0 : out STD_LOGIC;
    up_es_enb_0 : in STD_LOGIC;
    up_es_addr_0 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_0 : in STD_LOGIC;
    up_es_wdata_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_0 : out STD_LOGIC;
    up_es_reset_0 : in STD_LOGIC;
    up_rx_pll_locked_0 : out STD_LOGIC;
    up_rx_rst_0 : in STD_LOGIC;
    up_rx_user_ready_0 : in STD_LOGIC;
    up_rx_rst_done_0 : out STD_LOGIC;
    up_rx_prbssel_0 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    up_rx_prbscntreset_0 : in STD_LOGIC;
    up_rx_prbserr_0 : out STD_LOGIC;
    up_rx_prbslocked_0 : out STD_LOGIC;
    up_rx_bufstatus_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_rx_bufstatus_rst_0 : in STD_LOGIC;
    up_rx_lpm_dfe_n_0 : in STD_LOGIC;
    up_rx_rate_0 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_rx_sys_clk_sel_0 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_rx_out_clk_sel_0 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_rx_enb_0 : in STD_LOGIC;
    up_rx_addr_0 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_rx_wr_0 : in STD_LOGIC;
    up_rx_wdata_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_rx_rdata_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_rx_ready_0 : out STD_LOGIC;
    up_tx_pll_locked_0 : out STD_LOGIC;
    up_tx_rst_0 : in STD_LOGIC;
    up_tx_user_ready_0 : in STD_LOGIC;
    up_tx_rst_done_0 : out STD_LOGIC;
    up_tx_bufstatus_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_tx_prbsforceerr_0 : in STD_LOGIC;
    up_tx_prbssel_0 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    up_tx_lpm_dfe_n_0 : in STD_LOGIC;
    up_tx_rate_0 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_tx_sys_clk_sel_0 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_tx_out_clk_sel_0 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_tx_diffctrl_0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_postcursor_0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_precursor_0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_enb_0 : in STD_LOGIC;
    up_tx_addr_0 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_tx_wr_0 : in STD_LOGIC;
    up_tx_wdata_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_tx_rdata_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_tx_ready_0 : out STD_LOGIC;
    cpll_ref_clk_1 : in STD_LOGIC;
    up_cpll_rst_1 : in STD_LOGIC;
    rx_1_p : in STD_LOGIC;
    rx_1_n : in STD_LOGIC;
    rx_out_clk_1 : out STD_LOGIC;
    rx_clk_1 : in STD_LOGIC;
    rx_charisk_1 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_disperr_1 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_notintable_1 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_data_1 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    rx_calign_1 : in STD_LOGIC;
    rx_header_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    rx_block_sync_1 : out STD_LOGIC;
    tx_1_p : out STD_LOGIC;
    tx_1_n : out STD_LOGIC;
    tx_out_clk_1 : out STD_LOGIC;
    tx_clk_1 : in STD_LOGIC;
    tx_charisk_1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    tx_data_1 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    tx_header_1 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_es_enb_1 : in STD_LOGIC;
    up_es_addr_1 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_1 : in STD_LOGIC;
    up_es_wdata_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_1 : out STD_LOGIC;
    up_es_reset_1 : in STD_LOGIC;
    up_rx_pll_locked_1 : out STD_LOGIC;
    up_rx_rst_1 : in STD_LOGIC;
    up_rx_user_ready_1 : in STD_LOGIC;
    up_rx_rst_done_1 : out STD_LOGIC;
    up_rx_prbssel_1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    up_rx_prbscntreset_1 : in STD_LOGIC;
    up_rx_prbserr_1 : out STD_LOGIC;
    up_rx_prbslocked_1 : out STD_LOGIC;
    up_rx_bufstatus_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_rx_bufstatus_rst_1 : in STD_LOGIC;
    up_rx_lpm_dfe_n_1 : in STD_LOGIC;
    up_rx_rate_1 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_rx_sys_clk_sel_1 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_rx_out_clk_sel_1 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_rx_enb_1 : in STD_LOGIC;
    up_rx_addr_1 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_rx_wr_1 : in STD_LOGIC;
    up_rx_wdata_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_rx_rdata_1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_rx_ready_1 : out STD_LOGIC;
    up_tx_pll_locked_1 : out STD_LOGIC;
    up_tx_rst_1 : in STD_LOGIC;
    up_tx_user_ready_1 : in STD_LOGIC;
    up_tx_rst_done_1 : out STD_LOGIC;
    up_tx_bufstatus_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_tx_prbsforceerr_1 : in STD_LOGIC;
    up_tx_prbssel_1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    up_tx_lpm_dfe_n_1 : in STD_LOGIC;
    up_tx_rate_1 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_tx_sys_clk_sel_1 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_tx_out_clk_sel_1 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_tx_diffctrl_1 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_postcursor_1 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_precursor_1 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_enb_1 : in STD_LOGIC;
    up_tx_addr_1 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_tx_wr_1 : in STD_LOGIC;
    up_tx_wdata_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_tx_rdata_1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_tx_ready_1 : out STD_LOGIC;
    cpll_ref_clk_2 : in STD_LOGIC;
    up_cpll_rst_2 : in STD_LOGIC;
    rx_2_p : in STD_LOGIC;
    rx_2_n : in STD_LOGIC;
    rx_out_clk_2 : out STD_LOGIC;
    rx_clk_2 : in STD_LOGIC;
    rx_charisk_2 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_disperr_2 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_notintable_2 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_data_2 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    rx_calign_2 : in STD_LOGIC;
    rx_header_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    rx_block_sync_2 : out STD_LOGIC;
    tx_2_p : out STD_LOGIC;
    tx_2_n : out STD_LOGIC;
    tx_out_clk_2 : out STD_LOGIC;
    tx_clk_2 : in STD_LOGIC;
    tx_charisk_2 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    tx_data_2 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    tx_header_2 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_es_enb_2 : in STD_LOGIC;
    up_es_addr_2 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_2 : in STD_LOGIC;
    up_es_wdata_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_2 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_2 : out STD_LOGIC;
    up_es_reset_2 : in STD_LOGIC;
    up_rx_pll_locked_2 : out STD_LOGIC;
    up_rx_rst_2 : in STD_LOGIC;
    up_rx_user_ready_2 : in STD_LOGIC;
    up_rx_rst_done_2 : out STD_LOGIC;
    up_rx_prbssel_2 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    up_rx_prbscntreset_2 : in STD_LOGIC;
    up_rx_prbserr_2 : out STD_LOGIC;
    up_rx_prbslocked_2 : out STD_LOGIC;
    up_rx_bufstatus_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_rx_bufstatus_rst_2 : in STD_LOGIC;
    up_rx_lpm_dfe_n_2 : in STD_LOGIC;
    up_rx_rate_2 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_rx_sys_clk_sel_2 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_rx_out_clk_sel_2 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_rx_enb_2 : in STD_LOGIC;
    up_rx_addr_2 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_rx_wr_2 : in STD_LOGIC;
    up_rx_wdata_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_rx_rdata_2 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_rx_ready_2 : out STD_LOGIC;
    up_tx_pll_locked_2 : out STD_LOGIC;
    up_tx_rst_2 : in STD_LOGIC;
    up_tx_user_ready_2 : in STD_LOGIC;
    up_tx_rst_done_2 : out STD_LOGIC;
    up_tx_bufstatus_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_tx_prbsforceerr_2 : in STD_LOGIC;
    up_tx_prbssel_2 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    up_tx_lpm_dfe_n_2 : in STD_LOGIC;
    up_tx_rate_2 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_tx_sys_clk_sel_2 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_tx_out_clk_sel_2 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_tx_diffctrl_2 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_postcursor_2 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_precursor_2 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_enb_2 : in STD_LOGIC;
    up_tx_addr_2 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_tx_wr_2 : in STD_LOGIC;
    up_tx_wdata_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_tx_rdata_2 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_tx_ready_2 : out STD_LOGIC;
    cpll_ref_clk_3 : in STD_LOGIC;
    up_cpll_rst_3 : in STD_LOGIC;
    rx_3_p : in STD_LOGIC;
    rx_3_n : in STD_LOGIC;
    rx_out_clk_3 : out STD_LOGIC;
    rx_clk_3 : in STD_LOGIC;
    rx_charisk_3 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_disperr_3 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_notintable_3 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rx_data_3 : out STD_LOGIC_VECTOR ( 31 downto 0 );
    rx_calign_3 : in STD_LOGIC;
    rx_header_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    rx_block_sync_3 : out STD_LOGIC;
    tx_3_p : out STD_LOGIC;
    tx_3_n : out STD_LOGIC;
    tx_out_clk_3 : out STD_LOGIC;
    tx_clk_3 : in STD_LOGIC;
    tx_charisk_3 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    tx_data_3 : in STD_LOGIC_VECTOR ( 31 downto 0 );
    tx_header_3 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_es_enb_3 : in STD_LOGIC;
    up_es_addr_3 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_3 : in STD_LOGIC;
    up_es_wdata_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_3 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_3 : out STD_LOGIC;
    up_es_reset_3 : in STD_LOGIC;
    up_rx_pll_locked_3 : out STD_LOGIC;
    up_rx_rst_3 : in STD_LOGIC;
    up_rx_user_ready_3 : in STD_LOGIC;
    up_rx_rst_done_3 : out STD_LOGIC;
    up_rx_prbssel_3 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    up_rx_prbscntreset_3 : in STD_LOGIC;
    up_rx_prbserr_3 : out STD_LOGIC;
    up_rx_prbslocked_3 : out STD_LOGIC;
    up_rx_bufstatus_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_rx_bufstatus_rst_3 : in STD_LOGIC;
    up_rx_lpm_dfe_n_3 : in STD_LOGIC;
    up_rx_rate_3 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_rx_sys_clk_sel_3 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_rx_out_clk_sel_3 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_rx_enb_3 : in STD_LOGIC;
    up_rx_addr_3 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_rx_wr_3 : in STD_LOGIC;
    up_rx_wdata_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_rx_rdata_3 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_rx_ready_3 : out STD_LOGIC;
    up_tx_pll_locked_3 : out STD_LOGIC;
    up_tx_rst_3 : in STD_LOGIC;
    up_tx_user_ready_3 : in STD_LOGIC;
    up_tx_rst_done_3 : out STD_LOGIC;
    up_tx_bufstatus_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_tx_prbsforceerr_3 : in STD_LOGIC;
    up_tx_prbssel_3 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    up_tx_lpm_dfe_n_3 : in STD_LOGIC;
    up_tx_rate_3 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_tx_sys_clk_sel_3 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_tx_out_clk_sel_3 : in STD_LOGIC_VECTOR ( 2 downto 0 );
    up_tx_diffctrl_3 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_postcursor_3 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_precursor_3 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    up_tx_enb_3 : in STD_LOGIC;
    up_tx_addr_3 : in STD_LOGIC_VECTOR ( 11 downto 0 );
    up_tx_wr_3 : in STD_LOGIC;
    up_tx_wdata_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_tx_rdata_3 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_tx_ready_3 : out STD_LOGIC
  );

end system_util_daq2_xcvr_0;

architecture stub of system_util_daq2_xcvr_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "up_rstn,up_clk,qpll_ref_clk_0,up_qpll_rst_0,cpll_ref_clk_0,up_cpll_rst_0,rx_0_p,rx_0_n,rx_out_clk_0,rx_clk_0,rx_charisk_0[3:0],rx_disperr_0[3:0],rx_notintable_0[3:0],rx_data_0[31:0],rx_calign_0,rx_header_0[1:0],rx_block_sync_0,tx_0_p,tx_0_n,tx_out_clk_0,tx_clk_0,tx_charisk_0[3:0],tx_data_0[31:0],tx_header_0[1:0],up_cm_enb_0,up_cm_addr_0[11:0],up_cm_wr_0,up_cm_wdata_0[15:0],up_cm_rdata_0[15:0],up_cm_ready_0,up_es_enb_0,up_es_addr_0[11:0],up_es_wr_0,up_es_wdata_0[15:0],up_es_rdata_0[15:0],up_es_ready_0,up_es_reset_0,up_rx_pll_locked_0,up_rx_rst_0,up_rx_user_ready_0,up_rx_rst_done_0,up_rx_prbssel_0[3:0],up_rx_prbscntreset_0,up_rx_prbserr_0,up_rx_prbslocked_0,up_rx_bufstatus_0[1:0],up_rx_bufstatus_rst_0,up_rx_lpm_dfe_n_0,up_rx_rate_0[2:0],up_rx_sys_clk_sel_0[1:0],up_rx_out_clk_sel_0[2:0],up_rx_enb_0,up_rx_addr_0[11:0],up_rx_wr_0,up_rx_wdata_0[15:0],up_rx_rdata_0[15:0],up_rx_ready_0,up_tx_pll_locked_0,up_tx_rst_0,up_tx_user_ready_0,up_tx_rst_done_0,up_tx_bufstatus_0[1:0],up_tx_prbsforceerr_0,up_tx_prbssel_0[3:0],up_tx_lpm_dfe_n_0,up_tx_rate_0[2:0],up_tx_sys_clk_sel_0[1:0],up_tx_out_clk_sel_0[2:0],up_tx_diffctrl_0[4:0],up_tx_postcursor_0[4:0],up_tx_precursor_0[4:0],up_tx_enb_0,up_tx_addr_0[11:0],up_tx_wr_0,up_tx_wdata_0[15:0],up_tx_rdata_0[15:0],up_tx_ready_0,cpll_ref_clk_1,up_cpll_rst_1,rx_1_p,rx_1_n,rx_out_clk_1,rx_clk_1,rx_charisk_1[3:0],rx_disperr_1[3:0],rx_notintable_1[3:0],rx_data_1[31:0],rx_calign_1,rx_header_1[1:0],rx_block_sync_1,tx_1_p,tx_1_n,tx_out_clk_1,tx_clk_1,tx_charisk_1[3:0],tx_data_1[31:0],tx_header_1[1:0],up_es_enb_1,up_es_addr_1[11:0],up_es_wr_1,up_es_wdata_1[15:0],up_es_rdata_1[15:0],up_es_ready_1,up_es_reset_1,up_rx_pll_locked_1,up_rx_rst_1,up_rx_user_ready_1,up_rx_rst_done_1,up_rx_prbssel_1[3:0],up_rx_prbscntreset_1,up_rx_prbserr_1,up_rx_prbslocked_1,up_rx_bufstatus_1[1:0],up_rx_bufstatus_rst_1,up_rx_lpm_dfe_n_1,up_rx_rate_1[2:0],up_rx_sys_clk_sel_1[1:0],up_rx_out_clk_sel_1[2:0],up_rx_enb_1,up_rx_addr_1[11:0],up_rx_wr_1,up_rx_wdata_1[15:0],up_rx_rdata_1[15:0],up_rx_ready_1,up_tx_pll_locked_1,up_tx_rst_1,up_tx_user_ready_1,up_tx_rst_done_1,up_tx_bufstatus_1[1:0],up_tx_prbsforceerr_1,up_tx_prbssel_1[3:0],up_tx_lpm_dfe_n_1,up_tx_rate_1[2:0],up_tx_sys_clk_sel_1[1:0],up_tx_out_clk_sel_1[2:0],up_tx_diffctrl_1[4:0],up_tx_postcursor_1[4:0],up_tx_precursor_1[4:0],up_tx_enb_1,up_tx_addr_1[11:0],up_tx_wr_1,up_tx_wdata_1[15:0],up_tx_rdata_1[15:0],up_tx_ready_1,cpll_ref_clk_2,up_cpll_rst_2,rx_2_p,rx_2_n,rx_out_clk_2,rx_clk_2,rx_charisk_2[3:0],rx_disperr_2[3:0],rx_notintable_2[3:0],rx_data_2[31:0],rx_calign_2,rx_header_2[1:0],rx_block_sync_2,tx_2_p,tx_2_n,tx_out_clk_2,tx_clk_2,tx_charisk_2[3:0],tx_data_2[31:0],tx_header_2[1:0],up_es_enb_2,up_es_addr_2[11:0],up_es_wr_2,up_es_wdata_2[15:0],up_es_rdata_2[15:0],up_es_ready_2,up_es_reset_2,up_rx_pll_locked_2,up_rx_rst_2,up_rx_user_ready_2,up_rx_rst_done_2,up_rx_prbssel_2[3:0],up_rx_prbscntreset_2,up_rx_prbserr_2,up_rx_prbslocked_2,up_rx_bufstatus_2[1:0],up_rx_bufstatus_rst_2,up_rx_lpm_dfe_n_2,up_rx_rate_2[2:0],up_rx_sys_clk_sel_2[1:0],up_rx_out_clk_sel_2[2:0],up_rx_enb_2,up_rx_addr_2[11:0],up_rx_wr_2,up_rx_wdata_2[15:0],up_rx_rdata_2[15:0],up_rx_ready_2,up_tx_pll_locked_2,up_tx_rst_2,up_tx_user_ready_2,up_tx_rst_done_2,up_tx_bufstatus_2[1:0],up_tx_prbsforceerr_2,up_tx_prbssel_2[3:0],up_tx_lpm_dfe_n_2,up_tx_rate_2[2:0],up_tx_sys_clk_sel_2[1:0],up_tx_out_clk_sel_2[2:0],up_tx_diffctrl_2[4:0],up_tx_postcursor_2[4:0],up_tx_precursor_2[4:0],up_tx_enb_2,up_tx_addr_2[11:0],up_tx_wr_2,up_tx_wdata_2[15:0],up_tx_rdata_2[15:0],up_tx_ready_2,cpll_ref_clk_3,up_cpll_rst_3,rx_3_p,rx_3_n,rx_out_clk_3,rx_clk_3,rx_charisk_3[3:0],rx_disperr_3[3:0],rx_notintable_3[3:0],rx_data_3[31:0],rx_calign_3,rx_header_3[1:0],rx_block_sync_3,tx_3_p,tx_3_n,tx_out_clk_3,tx_clk_3,tx_charisk_3[3:0],tx_data_3[31:0],tx_header_3[1:0],up_es_enb_3,up_es_addr_3[11:0],up_es_wr_3,up_es_wdata_3[15:0],up_es_rdata_3[15:0],up_es_ready_3,up_es_reset_3,up_rx_pll_locked_3,up_rx_rst_3,up_rx_user_ready_3,up_rx_rst_done_3,up_rx_prbssel_3[3:0],up_rx_prbscntreset_3,up_rx_prbserr_3,up_rx_prbslocked_3,up_rx_bufstatus_3[1:0],up_rx_bufstatus_rst_3,up_rx_lpm_dfe_n_3,up_rx_rate_3[2:0],up_rx_sys_clk_sel_3[1:0],up_rx_out_clk_sel_3[2:0],up_rx_enb_3,up_rx_addr_3[11:0],up_rx_wr_3,up_rx_wdata_3[15:0],up_rx_rdata_3[15:0],up_rx_ready_3,up_tx_pll_locked_3,up_tx_rst_3,up_tx_user_ready_3,up_tx_rst_done_3,up_tx_bufstatus_3[1:0],up_tx_prbsforceerr_3,up_tx_prbssel_3[3:0],up_tx_lpm_dfe_n_3,up_tx_rate_3[2:0],up_tx_sys_clk_sel_3[1:0],up_tx_out_clk_sel_3[2:0],up_tx_diffctrl_3[4:0],up_tx_postcursor_3[4:0],up_tx_precursor_3[4:0],up_tx_enb_3,up_tx_addr_3[11:0],up_tx_wr_3,up_tx_wdata_3[15:0],up_tx_rdata_3[15:0],up_tx_ready_3";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "util_adxcvr,Vivado 2022.2";
begin
end;
