
// boolean to intiger

// C hex to verilog hex

///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////

package system_i_data_offload_1_pkg;

///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification
// environment.
///////////////////////////////////////////////////////////////////////////

  parameter system_i_data_offload_1_ID                     = 0;  
  parameter system_i_data_offload_1_MEM_TYPE               = 1;
  parameter system_i_data_offload_1_MEM_SIZE_LOG2          = 30;
  parameter system_i_data_offload_1_TX_OR_RXN_PATH         = 0;
  parameter system_i_data_offload_1_SRC_DATA_WIDTH         = 0;
  parameter system_i_data_offload_1_DST_DATA_WIDTH         = 0;
  parameter system_i_data_offload_1_DST_CYCLIC_EN          = 1;

//////////////////////////////////////////////////////////////////////////

endpackage : system_i_data_offload_1_pkg
