
// boolean to intiger

// C hex to verilog hex

///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////

package system_i_data_offload_0_pkg;

///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification
// environment.
///////////////////////////////////////////////////////////////////////////

  parameter system_i_data_offload_0_ID                     = 0;  
  parameter system_i_data_offload_0_MEM_TYPE               = 0;
  parameter system_i_data_offload_0_MEM_SIZE_LOG2          = 20;
  parameter system_i_data_offload_0_TX_OR_RXN_PATH         = 0;
  parameter system_i_data_offload_0_SRC_DATA_WIDTH         = 0;
  parameter system_i_data_offload_0_DST_DATA_WIDTH         = 0;
  parameter system_i_data_offload_0_DST_CYCLIC_EN          = 1;

//////////////////////////////////////////////////////////////////////////

endpackage : system_i_data_offload_0_pkg
