# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/system_constr.xdc

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/common/zc706/zc706_plddr3_constr.xdc

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/common/zc706/zc706_system_constr.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_200m_rstgen_0/system_sys_200m_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_200m_rstgen_0 || ORIG_REF_NAME==system_sys_200m_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hdmi_clkgen_0/system_axi_hdmi_clkgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hdmi_clkgen_0 || ORIG_REF_NAME==system_axi_hdmi_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hdmi_core_0/system_axi_hdmi_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_spdif_tx_core_0/system_axi_spdif_tx_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_core_0 || ORIG_REF_NAME==system_axi_spdif_tx_core_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_sysid_0_0/system_axi_sysid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_sysid_0_0 || ORIG_REF_NAME==system_axi_sysid_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rom_sys_0_0/system_rom_sys_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rom_sys_0_0 || ORIG_REF_NAME==system_rom_sys_0_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp0_interconnect_0/system_axi_hp0_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hp0_interconnect_0 || ORIG_REF_NAME==system_axi_hp0_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9144_xcvr_0/system_axi_ad9144_xcvr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9144_xcvr_0 || ORIG_REF_NAME==system_axi_ad9144_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_tx_axi_0/system_tx_axi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tx_axi_0 || ORIG_REF_NAME==system_tx_axi_0} -quiet] -quiet

# IP: bd/system/ip/system_tx_0/system_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tx_0 || ORIG_REF_NAME==system_tx_0} -quiet] -quiet

# IP: bd/system/ip/system_dac_tpl_core_0/system_dac_tpl_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dac_tpl_core_0 || ORIG_REF_NAME==system_dac_tpl_core_0} -quiet] -quiet

# IP: bd/system/ip/system_data_concat0_0/system_data_concat0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_data_concat0_0 || ORIG_REF_NAME==system_data_concat0_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_0_0/system_enable_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_enable_slice_0_0 || ORIG_REF_NAME==system_enable_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_0_0/system_valid_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_valid_slice_0_0 || ORIG_REF_NAME==system_valid_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_1_0/system_enable_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_enable_slice_1_0 || ORIG_REF_NAME==system_enable_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_1_0/system_valid_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_valid_slice_1_0 || ORIG_REF_NAME==system_valid_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9144_upack_0/system_axi_ad9144_upack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9144_upack_0 || ORIG_REF_NAME==system_axi_ad9144_upack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9144_dma_0/system_axi_ad9144_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9144_dma_0 || ORIG_REF_NAME==system_axi_ad9144_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_i_data_offload_0/system_i_data_offload_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_i_data_offload_0 || ORIG_REF_NAME==system_i_data_offload_0} -quiet] -quiet

# IP: bd/system/ip/system_storage_unit_0/system_storage_unit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_storage_unit_0 || ORIG_REF_NAME==system_storage_unit_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_xcvr_0/system_axi_ad9680_xcvr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9680_xcvr_0 || ORIG_REF_NAME==system_axi_ad9680_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_axi_0/system_rx_axi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_0/system_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] -quiet

# IP: bd/system/ip/system_adc_tpl_core_0/system_adc_tpl_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_adc_tpl_core_0 || ORIG_REF_NAME==system_adc_tpl_core_0} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_0_0/system_data_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_data_slice_0_0 || ORIG_REF_NAME==system_data_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_0_1/system_enable_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_enable_slice_0_1 || ORIG_REF_NAME==system_enable_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_0_1/system_valid_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_valid_slice_0_1 || ORIG_REF_NAME==system_valid_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_data_slice_1_0/system_data_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_data_slice_1_0 || ORIG_REF_NAME==system_data_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_enable_slice_1_1/system_enable_slice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_enable_slice_1_1 || ORIG_REF_NAME==system_enable_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_valid_slice_1_1/system_valid_slice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_valid_slice_1_1 || ORIG_REF_NAME==system_valid_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_cpack_0/system_axi_ad9680_cpack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9680_cpack_0 || ORIG_REF_NAME==system_axi_ad9680_cpack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_dma_0/system_axi_ad9680_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9680_dma_0 || ORIG_REF_NAME==system_axi_ad9680_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_i_data_offload_1/system_i_data_offload_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_i_data_offload_1 || ORIG_REF_NAME==system_i_data_offload_1} -quiet] -quiet

# IP: bd/system/ip/system_storage_unit_1/system_storage_unit_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_storage_unit_1 || ORIG_REF_NAME==system_storage_unit_1} -quiet] -quiet

# IP: bd/system/ip/system_util_daq2_xcvr_0/system_util_daq2_xcvr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_daq2_xcvr_0 || ORIG_REF_NAME==system_util_daq2_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9144_jesd_rstgen_0/system_axi_ad9144_jesd_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9144_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9144_jesd_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9680_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9680_jesd_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp3_interconnect_0/system_axi_hp3_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hp3_interconnect_0 || ORIG_REF_NAME==system_axi_hp3_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp1_interconnect_0/system_axi_hp1_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hp1_interconnect_0 || ORIG_REF_NAME==system_axi_hp1_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hp2_interconnect_0 || ORIG_REF_NAME==system_axi_hp2_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_rstgen_0/system_axi_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_rstgen_0 || ORIG_REF_NAME==system_axi_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_12_0/system_GND_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_GND_12_0 || ORIG_REF_NAME==system_GND_12_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_0/system_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_0_0 || ORIG_REF_NAME==system_system_ila_0_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_1_0/system_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_1_0 || ORIG_REF_NAME==system_system_ila_1_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_2_0/system_system_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_2_0 || ORIG_REF_NAME==system_system_ila_2_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_3_0/system_system_ila_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_3_0 || ORIG_REF_NAME==system_system_ila_3_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_4_0/system_system_ila_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_4_0 || ORIG_REF_NAME==system_system_ila_4_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: /home/shahamz/FinalProject/AnalogDevicesRepo/hdl/projects/daq2/zc706/daq2_zc706.gen/sources_1/bd/system/system_ooc.xdc
